set_property PACKAGE_PIN L2 [get_ports sys_rst_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n_0]
set_property PACKAGE_PIN B6 [get_ports {CLK_IN_D_0_clk_p[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {top_i/f_clk_buf_0/U0/IBUF_OUT[0]}]

set_property PACKAGE_PIN P4 [get_ports clk_25]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25]

set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DAT_clk_n[0]}]

set_property PACKAGE_PIN U4 [get_ports {ADC_DAT_clk_p[0]}]
set_property PACKAGE_PIN V3 [get_ports {ADC_DAT_clk_p[1]}]
set_property PACKAGE_PIN U7 [get_ports {ADC_DAT_clk_p[2]}]
set_property PACKAGE_PIN V8 [get_ports {ADC_DAT_clk_p[3]}]
set_property PACKAGE_PIN R5 [get_ports {ADC_DAT_clk_p[4]}]
set_property PACKAGE_PIN T4 [get_ports {ADC_DAT_clk_p[5]}]
set_property PACKAGE_PIN U6 [get_ports {ADC_DAT_clk_p[6]}]
set_property PACKAGE_PIN R7 [get_ports {ADC_DAT_clk_p[7]}]

set_property PACKAGE_PIN U2 [get_ports {f_clk_clk_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {f_clk_clk_p[0]}]
set_property PACKAGE_PIN K2 [get_ports {GPIO_0_tri_io[0]}]
set_property PACKAGE_PIN L3 [get_ports {GPIO_0_tri_io[1]}]
set_property PACKAGE_PIN J5 [get_ports {GPIO_0_tri_io[2]}]
set_property PACKAGE_PIN R6 [get_ports {GPIO_0_tri_io[3]}]
set_property PACKAGE_PIN K1 [get_ports {GPIO_0_tri_io[4]}]
set_property PACKAGE_PIN R3 [get_ports {GPIO_0_tri_io[5]}]
set_property PACKAGE_PIN N1 [get_ports {GPIO_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN N4 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property PACKAGE_PIN K5 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_o[1]}]
set_property IOSTANDARD SSTL135 [get_ports {gpio_rtl_1_tri_o[0]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_1_tri_o[0]}]
set_property PACKAGE_PIN L4 [get_ports {gpio_rtl_1_tri_o[12]}]
set_property PACKAGE_PIN P1 [get_ports {gpio_rtl_1_tri_o[11]}]
set_property PACKAGE_PIN M5 [get_ports {gpio_rtl_1_tri_o[10]}]
set_property PACKAGE_PIN M1 [get_ports {gpio_rtl_1_tri_o[9]}]
set_property PACKAGE_PIN J4 [get_ports {gpio_rtl_1_tri_o[8]}]
set_property PACKAGE_PIN P5 [get_ports {gpio_rtl_1_tri_o[7]}]
set_property PACKAGE_PIN N2 [get_ports {gpio_rtl_1_tri_o[6]}]
set_property PACKAGE_PIN P3 [get_ports {gpio_rtl_1_tri_o[5]}]
set_property PACKAGE_PIN M6 [get_ports {gpio_rtl_1_tri_o[4]}]
set_property PACKAGE_PIN T2 [get_ports {gpio_rtl_1_tri_o[3]}]
set_property PACKAGE_PIN M2 [get_ports {gpio_rtl_1_tri_o[2]}]
set_property PACKAGE_PIN N6 [get_ports {gpio_rtl_1_tri_o[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[0]}]
set_property PACKAGE_PIN M4 [get_ports {gpio_rtl_2_tri_o[0]}]
set_property PACKAGE_PIN K6 [get_ports {gpio_rtl_2_tri_o[1]}]
set_property PACKAGE_PIN N3 [get_ports {gpio_rtl_2_tri_o[2]}]

set_property IOSTANDARD LVDS_25 [get_ports {CLK_F_IN_clk_p[0]}]
set_property PACKAGE_PIN U2 [get_ports {CLK_F_IN_clk_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CLK_L_IN_clk_p[0]}]
set_property PACKAGE_PIN R2 [get_ports {CLK_L_IN_clk_p[0]}]


set_property PACKAGE_PIN P6 [get_ports sync]
set_property IOSTANDARD LVCMOS33 [get_ports sync]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
